### ISSUE TITLE
Standard library projects are not tooling friendly 

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-standard-library#1746]
**Description:**
At the moment, we use place holders in [Dependencies.toml](https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/Dependencies.toml), this is basically a problem when using something like VSCode.

Is there a possibility of getting rid of these ? Would it be possible to have a github workflow that keeps these things in sync ?

@ThisaruGuruge @niveathika @BuddhiWathsala Any thoughts ?

**Comment by ThisaruGuruge** [comment]
This issue is also there for the `CompilerPlugin.toml` and the `Ballerina.toml` files too. 

One possible solution is to keep the required version numbers in these files instead of the placeholders. Then the tooling support will be enabled.

But then the issue is to keep track of the versions. This can be achieved through a separate set of files with placeholders, kept in a separate place. These placeholders will be replaced with the correct versions when building, similar to what we do right now. The difference will be that we should replace the original files from the updated files, when building, if there's a change in the versions. Check the following example:

### Directory Structure
```
ballerina
├── Ballerina.toml
├── CompilerPlugin.toml
├── Dependencies.toml

resources
├── Ballerina.toml
├── CompilerPlugin.toml
├── Dependencies.toml
```

In the module root, we have `ballerina` directory, which we keep all the ballerina source files. Then we can have a `resource` directory (We can think of a better place to put this) which also has the same `toml` files. 

Now let's say In the `ballerina` directory, we have the following `Dewpendencies.toml` file:

```toml
[[dependency]]
org = "ballerina"
name = "io"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "cache"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.9.0"
```

In the resource directory we have the following file:
```toml
[[dependency]]
org = "ballerina"
name = "io"
version = "@stdlib.io.version@"

[[dependency]]
org = "ballerina"
name = "cache"
version = "@stdlib.cache.version@"

[[dependency]]
org = "ballerina"
name = "file"
version = "@stdlib.file.version@"
```

Now we have a TOML file without placeholders inside the ballerina directory and a file with placeholders inside our resource directory. 
When building the package, we read the files from the resources directory and replace the values in the placeholders accordingly. Then we replace the existing toml file inside the `ballerina` directory with the changed TOML file.

The only issue in this approach (I can think of) is when we are releasing a module, there will be a change in these files in the middle of a release. Then we have to commit these changes before the release because otherwise, the release build will fail. 

Consider the following scenario:

This is the `gradel.properties` file, before the release:
```properties
version=2.0.1-SNAPSHOT
```

This is the `Ballerina.toml` file:
```toml
[package]
org = "ballerina"
name = "http"
version = "http-native-2.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/http-native-2.0.1-SNAPSHOT.jar"
```

When releasing, we have to replace the `http-native-2.0.1-SNAPSHOT.jar` with `http-native-2.0.1.jar`. (Same goes with the `CompilerPlugin.toml` files too). We can commit this before the release build using Gradle. 

I think this way we can fix this issue.
