### ISSUE TITLE
Fix Trivy scan skip-dirs property usages

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#2483]
**Description:**
The Daily Trivy scan of standard libraries are failing due to vulnerabilities reported from `ballerina-lang` repository. Need to avoid this situation since it doesn't make sense to mark a standard library is failing because of a vulnerability in runtime.

Suggested fix: ` skip-dirs: '/github/workspace/ballerina/build'`

**Comment by niveathika** [comment]
Shall we point to `ballerina/build/bala_unzipped` for libraries that do not use external libraries? This ensures only that module's bala is scanned.

**Comment by ldclakmal** [comment]
> Shall we point to `ballerina/build/bala_unzipped` for libraries that do not use external libraries? This ensures only that module's bala is scanned.

Yes. In that case, we can use that for all the modules, even the ones which have external libraries. Isn't it? My only concern is that, have we finalized the directory structure inside the `build` directory? Just by looking at this, we can see some have used underscore while some have used dash in namings.

**Comment by ldclakmal** [comment]
Since we can't guarantee the directory structure inside the `build` directory there is an alternative simple option that works for both modules which have 3rd party dependencies or not.
We can create the `ballerina/lib` directory if it does not exist before point that to Trivy to scan. An extract of the yaml file is as follows. With this we can have same set of steps for all the standard libraries regardless of the 3rd party dependencies.

```yaml
      - name: Create lib directory if not exists
        run: mkdir -p ballerina/lib
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '/github/workspace/ballerina/lib'
          format: 'table'
          timeout: '10m0s'
          exit-code: '1'
```

@shafreenAnfar @daneshk @niveathika WDYT of this?
