### ISSUE TITLE
Add GraalVM check for the pull requests

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#4142]
**Description:**

When we do new features and update dependency versions in our standard library modules, it may break the GraalVM compatibility. Currently this can be noticed only after the daily build run. So the current expectation is to run the `GraalVM Check` action with your working branch (This action can be invoked from the forked repo as well. But the `master` and the working branch of the forked repo should be synced with the module's `master` branch in order to pickup the correct workflow file) and attach the build report to the PR description (then you can tick `Checked native-image compatibility` check).

And most of time, this check has been skipped and we have only noticed the failure in the daily build. And this makes it difficult to identify which PR caused this issue. So this task is to add `GraalVM check` as a default check in the PR. In order to skip the `GraalVM Check` you have to add this label: `Skip GraalVM Check`.

**Tasks:**

Follow the following guide lines to complete this task :
1. Add a new label - `Skip GraalVM Check` in the repository. (Goto `Pull requests`->`Labels` -> `New Label`)

    - **Label name** : `Skip GraalVM Check`
    - **Description**:  `This will skip the GraalVM compatibility check`
    - **Color**: `#D93F0B`

3. Add `pull_request` event to trigger the workflow. Change the `build-with-bal-test-native.yml` file by adding the following :
    (Change `<default-branch-name>` with the default branch name of the repository)
   ```yml
   on:
       ...
       pull_request:
           branches: 
               - <default-branch-name>
           types: [opened, synchronize, reopened, labeled, unlabeled]

   concurrency:
       group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
       cancel-in-progress: true
   ```
   > **Note:** Since the `GraalVM Check` is also triggered with labeled and unlabeled  actions, the check will restart by stopping the previous checks if you add/remove a label.

**Sample PR :** [`Add GraalVM check for the pull requests #66`](https://github.com/ballerina-platform/module-ballerina-constraint/pull/66)
