### ISSUE TITLE
[Improvement]: Regenerate connectors containing arrays with `maxItems` count

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5017]
### Connector Name

connectors/openapi (Open API Connector)

### Suggested improvement

The minimum and maximum number of items expected in an array can be mentioned in the OpenAPI spec as below. 

```yaml
recipients:
    type: array
    minItems: 1
    maxItems: 5
    items:
      type: object
      properties:
        fieldId:
          type: integer
          description: Lead Field Id with email address
          example: 1
        email:
          description: Recipient Email
          type: string
          format: email
          example: example@iriscrm.com
        name:
          description: Recipient Name
          type: string
          example: John Doe
```

Currently following records will be generated to interpret above scenario in Ballerina

```bal
public type ApplicationIdSendBody record {
    Recipient[5] recipients?;
    # Expire the previously generated application
    boolean expire?;
};

public type Recipient record {
    # Lead Field Id with email address
    int fieldId?;
    # Recipient Email
    string email?;
    # Recipient Name
    string name?;
};
```

In Ballerina, fixed length array should exactly contains the given number of elements and if not given, filler value will be added to remaining items. When sending request to an API with filler values is misleading. 

Therefore as per discussion with @MaryamZi generation of fixed length arrays will be removed by @lnash94 and after openapi-tool is updated with the fix, all the connectors with `maxItems` configuration need to be regenerated with the latest tool.

### Related issues

I am trying to do [...] but [...]
