### ISSUE TITLE
Improve client generation to support initialisation parameters

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#5056]
**Description:**
In gmail API
```
url : https://gmail.googleapis.com/gmail/v1
GET /users/{userId}/messages
```
The userId can be used as init variable. However this is not currently supported in generation even if this is used as parameterized url

```
servers:
  - url: https://gmail.googleapis.com/gmail/v1/users/{userId}
      variables:
          userId:
          default: "me"
```
