### ISSUE TITLE
Proposal: Map Ballerina HATEOAS Links to OpenAPI Specification

### ISSUE THREAD

**Issue by SachinAkash01** [ballerina-platform/ballerina-standard-library#5087]
## Summary
This proposal is to introduce the capabilities to support HATEOAS (Hypermedia As The Engine Of Application State) links in the generated OpenAPI specification of the Ballerina OpenAPI tool. Note that in the rest of the proposal HATEOAS is referred to as Hypermedia constraint.

## Goals

- Enhance the Ballerina OpenAPI tool by adding support for Hypermedia constraints in the generated OpenAPI specification.

## Motivation

OpenAPI is a widely used standard for documenting APIs. It allows developers to specify the structure and data types expected in API requests and responses.

Hypermedia constraints are one of the key principles in REST though it is often ignored. This principle emphasizes the interconnection of resources, offering API users an experience similar to navigating the web. The existing tool for generating OpenAPI specification from Ballerina code lacks support for including these Hypermedia constraints in the OpenAPI specification. This means that when developers use Hypermedia constraints in their Ballerina code, this information is not properly reflected in the OpenAPI specification.

Overall, improving the OpenAPI tool to support Hypermedia constraints of the Ballerina programming language in the generated OpenAPI specification is a worthwhile investment that will improve the overall developer experience.

## Description

The feature implementation focuses on integrating Ballerina Hypermedia constraints into generated OpenAPI specifications to accurately document the API. Following is the proposed way of reflecting Ballerina Hypermedia constraints into OpenAPI specification in three variations.

Sample Ballerina Code:
```ballerina
service /snowpeak on new http:Listener(port) {

    @http:ResourceConfig {
        name: "Locations",
        linkedTo: [ {names: "Rooms", relation: "room", method: "get"} ]
    }
    resource function get locations() returns @http:Cache rep:Locations|rep:SnowpeakInternalError {
       // some logic
    }

    @http:ResourceConfig {
        name: "Rooms"
    }
    resource function get locations/[string id]/rooms(string startDate, string endDate) 
                returns rep:Rooms|rep:SnowpeakInternalError {
        // some logic
    }
}
```

**[Variation 1] Generated OpenAPI Specification**
```yaml
paths:
  /locations:
    get:
      operationId: getLocations
      responses:
        "200":
          description: ok
          content:
          links:
            room:
              operationId: getRooms
  /locations/{id}/rooms:
    get:
      operationId: getRooms
      parameters:
```

**Pros:**
- This variation is relatively simple and easy to understand. It directly includes links under the response without a separate components section.

**Cons:**
- Same link cannot be reused across different paths or components.

**[Variation 2] Generated OpenAPI Specification**
```yaml
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        links:
          type: object
          additionalProperties:
            type: object
            properties:
              rel:
                type: string
                default: "room"
              href:
                type: string
                default: "/snowpeak/locations/{id}/rooms"
              method:
                type: string
                default: "GET"
```

**Pros:**
- This variation defines links as a specific schema with named properties, allowing detailed control over the structure of links.

**Cons:**
- It is harder to reflect the links in the OpenAPI specification if there are more than one Hypermedia constraint per resource.

**[Variation 3] Generated OpenAPI Specification**
```yaml
paths:
  /locations:
    get:
      operationId: getLocations
      responses:
        "200":
          description: ok
          content:
          links:
            room:
              $ref: '#/components/links/GetRooms'
  /locations/{id}/rooms:
    get:
      operationId: getRooms
      parameters:
      responses:
        "200":
          description: ok
          content:
components:
  links:
    GetRooms:
      operationId: getRooms
```

**Pros:**
- Links are defined in a separate `components` section, promoting a cleaner separation of concerns in the specification.
- Links are defined as components, making them reusable across different paths or components.

**Cons:**
- This structure is more complex, which might be overwhelming for simpler API designs.

**NOTE:** There is no proper and direct way to reflect resource name `@http:ResourceConfig { name: " Locations"` in OpenAPI specification

## Testing

- Unit Testing: Evaluate the individual components and core logic of the Ballerina OpenAPI tool, focusing on functions, methods, and modules to ensure correctness and Hypermedia constraint handling.

- Integration Testing: Assess the interaction and collaborations between various modules and components of the tool, verifying the seamless integration of Hypermedia constraints into the OpenAPI specification.
