### ISSUE TITLE
Open API is not generated properly when an Enum type is defined as a query param

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-standard-library#5269]
**Description:**

This is the service code. 

```
  # Get the Interface definition (with content) of an API.
    #
    # + apiId - Id of the API version
    # + authHeader - Header with valid token
    # + apiType - Type of the API. Possible values are HTTP, GRAPHQL, ASYNC, SOAP
    # + return - Interface definition of the API or error if unsuccessful.
    isolated resource function get apis/[string apiId]/idl(@http:Header {name: "x-jwt-assertion"} string authHeader, ApiTypes apiType) returns IDL|error|http:NotFound {  

===========

# Defines API types supported by Choreo.
public enum ApiTypes {
    HTTP,
    WS ,
    SOAPTOREST,
    SOAP,
    GRAPHQL,
    WEBSUB,
    SSE,
    WEBHOOK,
    ASYNC    
};
 
```

The generated openAPI schema has following

```
    ApiTypes:
      description: Defines API types supported by Choreo.
      oneOf:
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
      - {}
```

**Steps to reproduce:**

Pls use above resources 

**Affected Versions:**

Ballerina 2201.4.1
