### ISSUE TITLE
Invalid type generated when nillable decimal array has constraints

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5285]
**Description:**
$subject

Affected connectors : openfigi

### Sample OpenAPI 

```yaml
    NullableNumberInterval:
      type: array
      items:
        type: number
        nullable: true
      maxItems: 2
      minItems: 2
      nullable: true
      description: At least one entry should be non-null.
```

### Generated bal type

```bal
@constraint:Array {maxLength: 2, minLength: 2}
public type NullableNumberInterval decimal[]?;
```
![image](https://user-images.githubusercontent.com/34091327/229743762-7c136992-206c-4c1d-b8ee-eb94ed779df6.png)

Gives the error
`ERROR [types.bal:(155:1,155:47)] invalid `@constraint:Array` annotation on `decimal[]?` type`

**Steps to reproduce:**

**Affected Versions:**
2201.4.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
