### ISSUE TITLE
Multi line parameter comments are not handled. 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5294]
**Description:**

Sample OpenAPI snippet

```yaml
      - name: stream
        in: query
        description: "A flag indicating whether to stream events for the fine-tune\
          \ job. If set to true,\r\n            events will be sent as data-only server-sent\
          \ events as they become available. The stream will terminate with\r\n  \
          \          a data: [DONE] message when the job is finished (succeeded, cancelled,\
          \ or failed).\r\n            If set to false, only events generated so far\
          \ will be returned.."
        schema:
          type: boolean
```

Generated Code

![image](https://user-images.githubusercontent.com/34091327/228181032-ddcc8d6c-5ebd-4e0e-924d-7dce55a3beb4.png)

code contains errors.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
