### ISSUE TITLE
Double quote as value in record default value is not created properly

### ISSUE THREAD

**Issue by kapilraajP** [ballerina-platform/ballerina-standard-library#5369]
**Default value of `"` in Schemas** 
Following openAPI component is not being generated correctly in ballerina code
```yaml
components:
  schemas:
    Csv:
      properties:
        textQualifier:
          type: string
          default: ' " '
```

Generated 
```bal
public type TaskResponse record {
    string textQualifier? = """;
}
```
Expected
```bal
public type TaskResponse record {
    string textQualifier? = "\"";
}
```
**Affected Versions:**
2201.0.2
