### ISSUE TITLE
Add `discriminator` tag support 

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/ballerina-standard-library#5389]
**Description:**
Add `discriminator` tag support to tool.

**Describe your problem(s)**
Refer to this [openapi.yaml](https://gist.github.com/SkNuwanTissera/307ed1e1839240fcedac89cd07c381f2) LOC 2121
```
          discriminator:
            propertyName: type
            mapping:
              NEW_SELF_SIGN_CERTIFICATE: '#/components/schemas/NewCertificateForStation'
              FROM_KEYSTORE: '#/components/schemas/CertificateFromKeystoreForStation'
              FROM_CERTIFICATE_STORE: '#/components/schemas/CertificateFromCertStoreForStation'
```

**Describe your solution(s)**
The tool should support the `discriminator` tag.
