### ISSUE TITLE
Generate inline records for oneOf schemas with object schemas

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5434]
**Description:**

#### Sample OpenAPI Schema

```yaml
Subject:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        subject_type:
          oneOf:
           - properties:
              uuid:
                type: string
                description: Unique identifier for the activity
           - properties:
              first_name:
                type: string
                description: First name of the Uber user.
              last_name:
                type: string
                description: Last name of the Uber user.
```
#### Current Implementation
```java
throw new BallerinaOpenApiException(
                        "Unsupported object or composed schema is given inside a oneOf or anyOf schema.");
```
#### Suggested Implementation

```bal
public type Subject record {
  int id?;
  string name?;
  record{string uuid?;}|record{string first_name?; string last_name;} subject_type?;
};
```
