### ISSUE TITLE
Boolean and integer type headers are not added in the http request

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/ballerina-standard-library#5441]
**Description:**
``` ballerina
isolated function getMapForHeaders(map<any> headerParam) returns map<string|string[]> {
    map<string|string[]> headerMap = {};
    foreach var [key, value] in headerParam.entries() {
        if value is string || value is string[] {
            headerMap[key] = value;
        }
    }
    return headerMap;
}
```
Above util function handles headers in the string or string[] format . However there are boolean and integer types header parameters and those are not being added to the header map.

[Reference](https://github.com/ballerina-platform/ballerinax-openapi-connectors/blob/e7ca4615b2e95fac8f877cef96c69c5101febba7/openapi/cloudmersive.virusscan/openapi.yaml#L312)
```yaml
- name: allowInvalidFiles
        in: header
        description: Set to false to block invalid files, such as a PDF file that
          is not really a valid PDF file, or a Word Document that is not a valid Word
          Document.  Default is false (recommended).
        schema:
          type: boolean
```

 

**Affected Versions:**
SL Beta3
