### ISSUE TITLE
Support Enums in connector generation

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5479]
**Description:**
The `enum` keyword is used to restrict a value to a fixed set of values. It must be an array with at least one element, where each element is unique. 
```
...
JqlQueryClauseTimePredicate:
      required:
        - operator
      type: object
      properties:
        operator:
          type: string
          description: The operator between the field and the operand.
          enum:
            - before
            - after
            - from
            - to
            - 'on'
            - during
            - by
```
Related PR https://github.com/ballerina-platform/ballerina-openapi/pull/363

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Task List**

Enum Generation in parameters in Client generation
- [x] Query parameter
- [x] Header parameter
- [x] Path parameter

Enum generation in schema
- [x] Reusable enums 
- [x] Inline enums in properties
- [x] Nullable enums
