### ISSUE TITLE
Hyphens are not escaped for generated resource function names for services

### ISSUE THREAD

**Issue by hemikak** [ballerina-platform/ballerina-standard-library#5513]
**Description:**
$subject

Following is an OpenAPI spec and the generated resource function:
```yaml
paths:
  /org-invitation:
    post:
```

```ballerina
resource  function  post  org-invitation(@http:Payload  {} OrgInvitationEmail  payload)  returns  http:Ok|http:InternalServerError {
```
