### ISSUE TITLE
Unnecessary request initialization

### ISSUE THREAD

**Issue by Chuhaa** [ballerina-platform/ballerina-standard-library#5529]
**Description:**
New request is initialized in unnecessary places.

**Suggested Labels:**
bug

**OS, DB, other environment details and versions:**    
Ballerina Swan Lake Beta2, Ubuntu 20.04, OpenJDK 11

**Steps to reproduce:**
**.yml format**
```yml
 delete:
      operationId: deleteKey
      parameters:
        - description: ID of address
          in: path
          name: address
          required: true
          schema:
            type: string
        - description: ID of key
          in: path
          name: key
          required: true
          schema:
            type: string
```
**Generated code**
```ballerina
remote isolated function deleteKey(string address, string 'key) returns http:Response|error {
    string  path = string `/addresses/${address}/'keys/${'key}`;
    http:Request request = new;
    //TODO: Update the request as needed;
    http:Response response = check self.clientEp-> delete(path, request, targetType = http:Response);
    return response;
}
```
