### ISSUE TITLE
Default values for headers is not given in function signature. 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5583]
**Description:**
When a default value is given for header type operation parameter, default value has not mentioned in function signature
```
in: header
          name: Notion-Version
          schema:
            example: "100"
            type: string
            default: "2021-05-21"
```
#### Solution
```
 remote isolated function retrieveBlockChildren(string notionVersion = "2021-05-21") 
```

**Suggested Labels:**
> Bug

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
