### ISSUE TITLE
Client generation fails when the yaml has `object type` query parameters

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/ballerina-standard-library#5590]
**Description:**

When trying to generate a client for Stripe API using Open API specification, the client generation fails. This is because in the yaml file, an endpoint (/v1/account/persons) has a query parameter of type object.
https://stripe.com/docs/api/persons/object#person_object-relationship

```
  /v1/account/persons:
    get:
      description: <p>Returns a list of people associated with the account’s legal
        entity. The people are returned sorted by creation date, with the most
        recent people appearing first.</p>
      operationId: GetAccountPersons
      parameters:
        - description: A cursor for use in pagination. `ending_before` is an object ID
            that defines your place in the list. For instance, if you make a
            list request and receive 100 objects, starting with `obj_bar`, your
            subsequent call can include `ending_before=obj_bar` in order to
            fetch the previous page of the list.
          in: query
          name: ending_before
          required: false
          schema:
            maxLength: 5000
            type: string
          style: form
        - description: Specifies which fields in the response should be expanded.
          explode: true
          in: query
          name: expand
          required: false
          schema:
            items:
              maxLength: 5000
              type: string
            type: array
          style: deepObject
        - description: A limit on the number of objects to be returned. Limit can range
            between 1 and 100, and the default is 10.
          in: query
          name: limit
          required: false
          schema:
            type: integer
          style: form
        - description: Filters on the list of people returned based on the person's
            relationship to the account's company.
          explode: true
          in: query
          name: relationship
          required: false
          schema:
            properties:
              director:
                type: boolean
              executive:
                type: boolean
              owner:
                type: boolean
              representative:
                type: boolean
            title: all_people_relationship_specs
            type: object
          style: deepObject
        - description: A cursor for use in pagination. `starting_after` is an object ID
            that defines your place in the list. For instance, if you make a
            list request and receive 100 objects, ending with `obj_foo`, your
            subsequent call can include `starting_after=obj_foo` in order to
            fetch the next page of the list.
          in: query
          name: starting_after
          required: false
          schema:
            maxLength: 5000
            type: string
          style: form
```

![Screenshot from 2021-07-12 17-47-00](https://user-images.githubusercontent.com/44081958/125287304-5fcfe300-e33a-11eb-83d1-21d47f88607e.png)

In ballerina, query parameters are only supported for the following data types
```
 type BasicType boolean|int|float|decimal|string;
 public type QueryParamType ()|BasicType|BasicType[];
```
Because of this issue, the client generation fails.
