### ISSUE TITLE
[Bal -> OpenAPI] Generator doesn't generate more than one record

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-standard-library#5641]
**Description:**
When the bal file has more than one record, open api generator generates only one record in the yaml/json file. 

**Steps to reproduce:**
```ballerina
import ballerina/http;

listener http:Listener personEp = new (9090);

type Person record {
    int id;
    string fname;
    string lname;
    int age;
};

type PersonInput record {
    string fname;
    string lname;
    int age;
};

Person[] personList = [];

service http:Service /api/person on personEp {

    resource function post .(@http:Payload {} PersonInput person) returns json {

        Person newPerson = {
            id: personList.length(),
            fname: person.fname,
            lname: person.lname,
            age: person.age
        };

        personList.push(newPerson);
        json|error greeting = newPerson.cloneWithType(json);
        if (greeting is json) {
            return greeting;
        }
    }

    resource function put .(@http:Payload {} Person person) returns json {
        int index = getIndexOfPerson(person.id);
        personList[index] = person;
        json result = {"Message": "Entry updated"};
        return result;
    }
}

function getIndexOfPerson(int id) returns int {
    int index = -1;
    foreach int i in 0 ... personList.length() {
        Person entry = personList[i];
        int entryId = entry.id;
        if (entryId == id) {
            return entryId;
        }
    }
    return index;
}
```

This code generates only one record in the yaml 
```yaml
components:
  schemas:
    Person:
      type: object
      properties:
        fname:
          type: string
        lname:
          type: string
        id:
          type: integer
          format: int32
        age:
          type: integer
          format: int32
```
**Affected Product Version:**
slalpha3 

**OS, DB, other environment details and versions:**    
Ubuntu 20.04
