### ISSUE TITLE
Enable basic auth file user store support

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#862]
Need to enable "basic auth file user store" support after Swan Lake alpha which was disabled due to a limitation of `configurable` feature does not support for mapping types.

This was disable by the PRs.
1. https://github.com/ballerina-platform/module-ballerina-auth/pull/60
2. https://github.com/ballerina-platform/module-ballerina-http/pull/183

Related PRs:
1. https://github.com/ballerina-platform/ballerina-distribution/pull/1182
2. https://github.com/ballerina-platform/ballerina-distribution/pull/1187

**Comment by sameerajayasoma** [comment]
Is a mapping type the best choice for this use case? If you use a mapping value, the `Config.toml` would have the following bits. Here `auth` is the module name and `users` is the variable name of map type.

```toml
# 1) Inline table version
[auth.users]
alice = { password ="password1", scopes="scope1"}
bob = { password ="password2", scopes="scope1"}


# 2) Standard table version
[auth.users.alice]
password="password1"
scopes="scope1"

[auth.users.bob]
password="password2"
scopes="scope1"
```

How about using arrays here?  I think following is better. WDYT @shafreenAnfar @ldclakmal ?
```toml
[[auth.users]]
username = "alice"
password="password1"
scopes="scope1"

[[auth.users]]
username = "bob"
password="password2"
scopes="scope1"
```
